Code to create visualizations from data obtained from sensors.

In [9]:
import matplotlib.pyplot as plt
import numpy as np
import csv

dataSource = 'Tests/3dplot_trial.csv'

with open(dataSource, 'r') as file:
    reader = csv.reader(file)
    next(reader)
    data = list(reader)

data_array = np.array(data, dtype=float)

print(data_array)

"""
fig = plt.figure()
ax = fig.add_subplot(projection='3d')

# Create the mesh in polar coordinates and compute corresponding Z.
r = np.linspace(0, 1.25, 50)
p = np.linspace(0, 2*np.pi, 50)
R, P = np.meshgrid(r, p)
Z = ((R**2 - 1)**2)

# Express the mesh in the cartesian system.
X, Y = R*np.cos(P), R*np.sin(P)

# Plot the surface.
ax.plot_surface(X, Y, Z, cmap=plt.cm.YlGnBu_r)

# Tweak the limits and add latex math labels.
ax.set_zlim(0, 1)
ax.set_xlabel(r'$\phi_\mathrm{real}$')
ax.set_ylabel(r'$\phi_\mathrm{im}$')
ax.set_zlabel(r'$V(\phi)$')

plt.show()
"""

[[ 10.   0.   0.]
 [ 10.  30.   0.]
 [ 10. -30.   0.]
 [ 10.   0.  30.]
 [ 10.  30.  30.]
 [ 10. -30.  30.]
 [ 10.   0. -30.]
 [ 10.  30. -30.]
 [ 10. -30. -30.]]


<>:16: SyntaxWarning: invalid escape sequence '\p'
<>:16: SyntaxWarning: invalid escape sequence '\p'
C:\Users\jespinozadiaz\AppData\Local\Temp\ipykernel_21952\2990562614.py:16: SyntaxWarning: invalid escape sequence '\p'
  """


"\nfig = plt.figure()\nax = fig.add_subplot(projection='3d')\n\n# Create the mesh in polar coordinates and compute corresponding Z.\nr = np.linspace(0, 1.25, 50)\np = np.linspace(0, 2*np.pi, 50)\nR, P = np.meshgrid(r, p)\nZ = ((R**2 - 1)**2)\n\n# Express the mesh in the cartesian system.\nX, Y = R*np.cos(P), R*np.sin(P)\n\n# Plot the surface.\nax.plot_surface(X, Y, Z, cmap=plt.cm.YlGnBu_r)\n\n# Tweak the limits and add latex math labels.\nax.set_zlim(0, 1)\nax.set_xlabel(r'$\\phi_\\mathrm{real}$')\nax.set_ylabel(r'$\\phi_\\mathrm{im}$')\nax.set_zlabel(r'$V(\\phi)$')\n\nplt.show()\n"